-- MySQL Script generated by MySQL Workbench
-- Wed Jun 23 11:29:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ciberimpacto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ciberimpacto` ;

-- -----------------------------------------------------
-- Schema ciberimpacto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciberimpacto` DEFAULT CHARACTER SET utf8 ;
USE `ciberimpacto` ;

-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_categoria` (
  `codCategoria` INT NOT NULL,
  `nombreCategoria` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`codCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_ciudad` (
  `codCiudad` VARCHAR(3) NOT NULL,
  `nombreCiudad` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codCiudad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_marca` (
  `codMarca` INT NOT NULL,
  `nombreMarca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codMarca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_cpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_cpu` (
  `codCPU` INT NOT NULL,
  `codMarca` INT NOT NULL,
  `nombreCPU` VARCHAR(45) NOT NULL,
  `modeloCPU` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCPU`),
  INDEX `fk_tbCPU_tbMarca:codMarca_idx` (`codMarca` ASC) VISIBLE,
  CONSTRAINT `fk_tbCPU_tbMarca:codMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_pais` (
  `codPais` VARCHAR(2) NOT NULL,
  `nombre` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codPais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_tipodocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_tipodocumento` (
  `codTipoDocumento` INT NOT NULL,
  `nombreTipo` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`codTipoDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_tipousuario` (
  `codTipoUsuario` INT NOT NULL,
  `nombreTipo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`codTipoUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_usuarios` (
  `codUsuario` VARCHAR(5) NOT NULL,
  `codTipoUsuario` INT NULL DEFAULT '2',
  `email` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(16) NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `apellidoCompleto` VARCHAR(45) NOT NULL,
  `codTipoDocumento` INT NULL DEFAULT NULL,
  `numeroDocumento` VARCHAR(9) NULL DEFAULT NULL,
  `numeroTelefonico` VARCHAR(9) NULL DEFAULT NULL,
  `codPais` VARCHAR(2) NULL DEFAULT NULL,
  `codCiudad` VARCHAR(3) NULL DEFAULT NULL,
  `numeroRUC` VARCHAR(11) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codUsuario`),
  INDEX `fk_tbUsuarios_tbTipoUsuario:codTipoUsuario_idx` (`codTipoUsuario` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_tbCiudad:codCiudad_idx` (`codCiudad` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_tbPais:codPais_idx` (`codPais` ASC) VISIBLE,
  INDEX `fk_tbUsuarios_tbTipoDocumento:codDocumento_idx` (`codTipoDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_tbUsuarios_tbCiudad:codCiudad`
    FOREIGN KEY (`codCiudad`)
    REFERENCES `ciberimpacto`.`tb_ciudad` (`codCiudad`),
  CONSTRAINT `fk_tbUsuarios_tbPais:codPais`
    FOREIGN KEY (`codPais`)
    REFERENCES `ciberimpacto`.`tb_pais` (`codPais`),
  CONSTRAINT `fk_tbUsuarios_tbTipoDocumento:codDocumento`
    FOREIGN KEY (`codTipoDocumento`)
    REFERENCES `ciberimpacto`.`tb_tipodocumento` (`codTipoDocumento`),
  CONSTRAINT `fk_tbUsuarios_tbTipoUsuario:codTipoUsuario`
    FOREIGN KEY (`codTipoUsuario`)
    REFERENCES `ciberimpacto`.`tb_tipousuario` (`codTipoUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_factura` (
  `codFactura` VARCHAR(10) NOT NULL,
  `codUsuario` VARCHAR(5) NOT NULL,
  `fechaPedido` DATETIME NOT NULL,
  `total` DECIMAL(7,2) NOT NULL,
  `PrecioEnvio` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`codFactura`),
  INDEX `fk_tbFactura_tbUsuario:codUsuario_idx` (`codUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_tbFactura_tbUsuario:codUsuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `ciberimpacto`.`tb_usuarios` (`codUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_producto` (
  `codProducto` VARCHAR(5) NOT NULL,
  `modeloProducto` VARCHAR(45) NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `descripcionPantalla` VARCHAR(15) NOT NULL,
  `CPUU` VARCHAR(45) NOT NULL,
  `GPU` VARCHAR(45) NOT NULL,
  `DiscoDuro` VARCHAR(45) NOT NULL,
  `SistemaOperativo` VARCHAR(45) NOT NULL,
  `precioVenta` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_detallefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_detallefactura` (
  `codFactura` VARCHAR(10) NOT NULL,
  `codDetalleFactura` INT NOT NULL,
  `codProducto` VARCHAR(5) NOT NULL,
  `cantidad` INT NOT NULL,
  `SubTotal` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codFactura`, `codDetalleFactura`),
  INDEX `fk_tbDetalleFactura_tbProducto:codProducto_idx` (`codProducto` ASC) VISIBLE,
  CONSTRAINT `fk_tbDetalleFactura_tbFactura:codFactura`
    FOREIGN KEY (`codFactura`)
    REFERENCES `ciberimpacto`.`tb_factura` (`codFactura`),
  CONSTRAINT `fk_tbDetalleFactura_tbProducto:codProducto`
    FOREIGN KEY (`codProducto`)
    REFERENCES `ciberimpacto`.`tb_producto` (`codProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_tipodiscoduro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_tipodiscoduro` (
  `codTipoDiscoDuro` INT NOT NULL,
  `nombreTipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codTipoDiscoDuro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_discoduro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_discoduro` (
  `codDiscoDuro` INT NOT NULL,
  `codMarca` INT NOT NULL,
  `capacidad` VARCHAR(10) NOT NULL,
  `codTipoDiscoDuro` INT NOT NULL,
  PRIMARY KEY (`codDiscoDuro`),
  INDEX `fk_tbDiscoDuro_tbTipoDIscoDuro:codTipoDiscoDuro_idx` (`codTipoDiscoDuro` ASC) VISIBLE,
  INDEX `fk_tbDiscoDuro_tbMarca_idx` (`codMarca` ASC) VISIBLE,
  CONSTRAINT `fk_tbDiscoDuro_tbMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`),
  CONSTRAINT `fk_tbDiscoDuro_tbTipoDIscoDuro:codTipoDiscoDuro`
    FOREIGN KEY (`codTipoDiscoDuro`)
    REFERENCES `ciberimpacto`.`tb_tipodiscoduro` (`codTipoDiscoDuro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_gpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_gpu` (
  `codGPU` INT NOT NULL,
  `codMarca` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codGPU`),
  INDEX `fk_tbGPU_tbMarca:codMarca_idx` (`codMarca` ASC) VISIBLE,
  CONSTRAINT `fk_tbGPU_tbMarca:codMarca`
    FOREIGN KEY (`codMarca`)
    REFERENCES `ciberimpacto`.`tb_marca` (`codMarca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tb_sistemaoperativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tb_sistemaoperativo` (
  `codSistemaOperativo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codSistemaOperativo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ciberimpacto`.`tbcarrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciberimpacto`.`tbcarrito` (
  `codUsuario` VARCHAR(5) NOT NULL,
  `codCarrito` INT NOT NULL AUTO_INCREMENT,
  `codProducto` VARCHAR(5) NOT NULL,
  `cantidad` INT NOT NULL,
  `SubTotal` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codCarrito`, `codUsuario`),
  INDEX `fk_tbCarrito_tbUsuario:codUsuario_idx` (`codUsuario` ASC) VISIBLE,
  INDEX `fk_tbCarrito_tbProducto:codProducto_idx` (`codProducto` ASC) VISIBLE,
  CONSTRAINT `fk_tbCarrito_tbProducto:codProducto`
    FOREIGN KEY (`codProducto`)
    REFERENCES `ciberimpacto`.`tb_producto` (`codProducto`),
  CONSTRAINT `fk_tbCarrito_tbUsuario:codUsuario`
    FOREIGN KEY (`codUsuario`)
    REFERENCES `ciberimpacto`.`tb_usuarios` (`codUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
